# Generated by Django 3.0.7 on 2020-07-03 02:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomingCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('from_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_numbers', to='calls.PhoneNumber')),
                ('to_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_numbers', to='calls.PhoneNumber')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
